# Write your MySQL query statement below
WITH FRIENDS_ACCEPTED AS(
    SELECT accepter_id , COUNT(ACCEPTER_ID) AS FRIENDS_ACCEPTED
    FROM REQUESTACCEPTED
    GROUP BY ACCEPTER_ID
),
FRIENDS_REQUESTED AS(
    SELECT requester_id, COUNT(REQUESTER_ID) AS FRIENDS_REQUESTED
    FROM REQUESTACCEPTED
    GROUP BY REQUESTER_ID
),
SUMMED AS(
SELECT ACCEPTER_ID, REQUESTER_ID, FRIENDS_ACCEPTED, FRIENDS_REQUESTED,
CASE WHEN FRIENDS_ACCEPTED IS NULL THEN FRIENDS_REQUESTED
WHEN FRIENDS_REQUESTED IS NULL THEN FRIENDS_ACCEPTED
ELSE (FRIENDS_ACCEPTED + FRIENDS_REQUESTED) END AS FRIENDS
FROM FRIENDS_ACCEPTED a
LEFT JOIN FRIENDS_REQUESTED r
ON a.accepter_id = r.requester_id
UNION
(SELECT ACCEPTER_ID, REQUESTER_ID, FRIENDS_ACCEPTED, FRIENDS_REQUESTED,
CASE WHEN FRIENDS_ACCEPTED IS NULL THEN FRIENDS_REQUESTED
WHEN FRIENDS_REQUESTED IS NULL THEN FRIENDS_ACCEPTED
ELSE (FRIENDS_ACCEPTED + FRIENDS_REQUESTED) END AS FRIENDS
FROM FRIENDS_ACCEPTED a
right JOIN FRIENDS_REQUESTED r
ON a.accepter_id = r.requester_id)
),
LARGEST AS(
    SELECT FRIENDS FROM
    SUMMED
    ORDER BY FRIENDS DESC
    LIMIT 1
)
SELECT 
CASE WHEN ACCEPTER_ID IS NULL THEN REQUESTER_ID
ELSE ACCEPTER_ID END AS id,
FRIENDS AS num
FROM SUMMED
WHERE FRIENDS IN (
    SELECT FRIENDS FROM LARGEST
)