# Write your MySQL query statement below
WITH SUMMED AS(SELECT *,
SUM(weight) OVER(ORDER BY turn ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS SUMMED
FROM QUEUE
GROUP BY person_id
ORDER BY turn DESC)

SELECT person_name
FROM SUMMED
WHERE SUMMED <= 1000
LIMIT 1